### PR TITLE
utf8 and dot fix

### PR DESCRIPTION
**Pull request by GooseFuse**
-added utf8 encoding
-fixed bug when semeone guessed with a dot (!guess .)
-added exception message when loading words.txt

### CODE REVIEW

**Comment by mithom** [comment]
i will check this out later today, sorry for the month long wait, didn't see this

**Comment by mithom** [comment]
@GooseFuse i will apply the UTF-8 fix, not sure how i could've overlooked that
but about the bugfix for the . i don't really see what the bug is? i've tested myself and it works like expected. I do know what you try to solve though because i think it interprets it as a regex and dot means everything, but i don't see this behavior in testing

**Comment by GooseFuse** [comment]
When the word to guess contains dots for example i.like.trains and someone tries to guess the dot it flags all the missing letters and the game thinks someone guessed the entire word. It only happens when there's a dot in the word.

In fill_in_letter(letter) there's this:

for m in re.finditer("["+letter+"]", m_CurrentSolution):

so if you look for dot it just finds all the letters if there's no square brackets

**Comment by mithom** [comment]
Okay i see why this happening. The initial check doesnt happen with regex while the replacing does. This seems like a good solution to me. Thx for the pr

**Pull request merged**
